# Generated by Django 6.0.2 on 2026-02-08 03:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_start', models.IntegerField(default=500, help_text='Starting number for serial generation (default: 500, becomes 000500)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Serial Start Position')),
                ('serial_digits', models.IntegerField(default=6, help_text='Number of digits for serial numbers with leading zeros (default: 6)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Serial Digit Count')),
                ('current_serial', models.IntegerField(default=500, help_text='Auto-incrementing counter for next serial number', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Serial Counter')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('part_number', models.CharField(help_text='Format: XXX-XXXX (e.g., 232-9983)', max_length=50, primary_key=True, serialize=False, verbose_name='Part Number')),
                ('upc', models.CharField(blank=True, help_text='12-digit Universal Product Code (optional)', max_length=12, null=True, verbose_name='UPC')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('serial_number', models.CharField(help_text='Sequential number with leading zeros (e.g., 000500)', max_length=20, primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('upc', models.CharField(blank=True, help_text='Denormalized UPC for quick label printing', max_length=12, null=True, verbose_name='UPC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='inventory.product', verbose_name='Part Number')),
            ],
            options={
                'verbose_name': 'Serial Number',
                'verbose_name_plural': 'Serial Numbers',
                'ordering': ['-created_at'],
            },
        ),
    ]
