# Generated by Django 6.0.2 on 2026-02-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='admin_password',
            field=models.CharField(default='admin', help_text='Password for UPC management admin interface', max_length=100, verbose_name='Admin Password'),
        ),
    ]
