# Generated by Django 6.0.2 on 2026-02-08 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_config_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='box_label_zpl',
            field=models.TextField(default='^XA\n^FO50,30^A0N,35,35^FD{{part}}^FS\n^FO50,80^BY2^BCN,70,Y,N,N^FD{{part}}^FS\n^FO50,170^BY2^BCN,70,Y,N,N^FD{{serial}}^FS\n^FO50,260^A0N,30,30^FDSN.# {{serial}}^FS\n{{upc_section}}\n^XZ', help_text='ZPL template for shipping box labels. Use {{part}}, {{serial}}, {{upc_section}} as placeholders.', verbose_name='Box Label ZPL Template'),
        ),
        migrations.AddField(
            model_name='config',
            name='label_dpi',
            field=models.IntegerField(choices=[(203, '203 DPI'), (300, '300 DPI'), (600, '600 DPI')], default=203, help_text='Printer resolution in dots per inch', verbose_name='Label DPI'),
        ),
        migrations.AddField(
            model_name='config',
            name='label_height',
            field=models.IntegerField(default=3, help_text='Height of labels in inches (default: 3)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Label Height (inches)'),
        ),
        migrations.AddField(
            model_name='config',
            name='label_width',
            field=models.IntegerField(default=4, help_text='Width of labels in inches (default: 4)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Label Width (inches)'),
        ),
        migrations.AddField(
            model_name='config',
            name='serial_label_zpl',
            field=models.TextField(default='^XA\n^FO50,30^A0N,25,25^FDNe pas enlever (Garantie)^FS\n^FO50,60^A0N,25,25^FDDo not remove (Warranty)^FS\n^FO50,120^BY2^BCN,70,Y,N,N^FD{{serial}}^FS\n^FO50,210^A0N,30,30^FDSN.# {{serial}}^FS\n^XZ', help_text='ZPL template for inventory serial number labels. Use {{serial}} for serial number.', verbose_name='Serial Label ZPL Template'),
        ),
    ]
