# Generated by Django 6.0.2 on 2026-02-08 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_config_box_label_zpl_config_label_dpi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='label_height',
        ),
        migrations.RemoveField(
            model_name='config',
            name='label_width',
        ),
        migrations.AddField(
            model_name='config',
            name='box_label_height',
            field=models.IntegerField(default=3, help_text='Height of box labels in inches', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Box Label Height (inches)'),
        ),
        migrations.AddField(
            model_name='config',
            name='box_label_width',
            field=models.IntegerField(default=4, help_text='Width of box labels in inches', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Box Label Width (inches)'),
        ),
        migrations.AddField(
            model_name='config',
            name='serial_label_height',
            field=models.IntegerField(default=2, help_text='Height of serial labels in inches', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Serial Label Height (inches)'),
        ),
        migrations.AddField(
            model_name='config',
            name='serial_label_width',
            field=models.IntegerField(default=4, help_text='Width of serial labels in inches', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Serial Label Width (inches)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='label_dpi',
            field=models.IntegerField(choices=[(203, '203 DPI'), (300, '300 DPI'), (600, '600 DPI')], default=203, help_text='Printer resolution in dots per inch', verbose_name='Printer DPI'),
        ),
    ]
