# Generated by Django 6.0.2 on 2026-02-08 22:53

from django.db import migrations


def update_zpl_templates(apps, schema_editor):
    """Update existing Config record with centered ZPL templates and UPC-A support."""
    Config = apps.get_model('inventory', 'Config')
    
    # Get the existing config (should only be one)
    config = Config.objects.first()
    if config:
        # Updated serial label template (centered)
        config.serial_label_zpl = """^XA
^FO140,30^A0N,25,25^FDNe pas enlever (Garantie)^FS
^FO140,60^A0N,25,25^FDDo not remove (Warranty)^FS
^FO250,120^BY2^BCN,70,Y,N,N^FD{{serial}}^FS
^FO310,210^A0N,30,30^FDSN.# {{serial}}^FS
^XZ"""
        
        # Updated box label template (centered with UPC-A placeholder)
        config.box_label_zpl = """^XA
^FO320,30^A0N,35,35^FD{{part}}^FS
^FO250,80^BY2^BCN,70,Y,N,N^FD{{part}}^FS
^FO250,170^BY2^BCN,70,Y,N,N^FD{{serial}}^FS
^FO310,260^A0N,30,30^FDSN.# {{serial}}^FS
{{upc_section}}
^XZ"""
        
        config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_config_label_height_remove_config_label_width_and_more'),
    ]

    operations = [
        migrations.RunPython(update_zpl_templates),
    ]
