# Generated by Django 6.0.2 on 2026-02-10 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_update_zpl_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='box_label_height',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Height of box labels in inches (e.g., 3.0 or 2.5)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Box Label Height (inches)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='box_label_width',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Width of box labels in inches (e.g., 4.0 or 3.5)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Box Label Width (inches)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='box_label_zpl',
            field=models.TextField(default='^XA\n^FO320,30^A0N,35,35^FD{{part}}^FS\n^FO250,80^BY2^BCN,70,Y,N,N^FD{{part}}^FS\n^FO250,170^BY2^BCN,70,Y,N,N^FD{{serial}}^FS\n^FO310,260^A0N,30,30^FDSN.# {{serial}}^FS\n^FO230,320^BY2^BUN,70^FD{{upc_11_digits}}^FS\n^FO260,400^A0N,25,25^FDUPC: {{upc_full}}^FS\n^XZ', help_text='ZPL template for shipping box labels. Use {{part}}, {{serial}}, {{upc_full}}, {{upc_11_digits}} as placeholders.', verbose_name='Box Label ZPL Template'),
        ),
        migrations.AlterField(
            model_name='config',
            name='label_dpi',
            field=models.IntegerField(default=203, help_text='Printer resolution in dots per inch (common: 203, 300, 600)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Printer DPI'),
        ),
        migrations.AlterField(
            model_name='config',
            name='serial_label_height',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Height of serial labels in inches (e.g., 2.0 or 2.5)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Serial Label Height (inches)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='serial_label_width',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Width of serial labels in inches (e.g., 4.0 or 3.5)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Serial Label Width (inches)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='serial_label_zpl',
            field=models.TextField(default='^XA\n^FO140,30^A0N,25,25^FDNe pas enlever (Garantie)^FS\n^FO140,60^A0N,25,25^FDDo not remove (Warranty)^FS\n^FO250,120^BY2^BCN,70,Y,N,N^FD{{serial}}^FS\n^FO310,210^A0N,30,30^FDSN.# {{serial}}^FS\n^XZ', help_text='ZPL template for inventory serial number labels. Use {{serial}} for serial number.', verbose_name='Serial Label ZPL Template'),
        ),
    ]
