# Generated by Django 6.0.2 on 2026-03-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_config_box_label_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='box_label_height',
        ),
        migrations.RemoveField(
            model_name='config',
            name='box_label_width',
        ),
        migrations.RemoveField(
            model_name='config',
            name='serial_label_height',
        ),
        migrations.RemoveField(
            model_name='config',
            name='serial_label_width',
        ),
    ]
