# Generated by Django 6.0.2 on 2026-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_config_box_label_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='box_label_zpl',
            field=models.TextField(default='^XA\n^MTT\n^PW812\n^LL607\n^LH0,0\n^CI28\n \n^FO20,190^A0N,30,30^FDNuméro de pièce:^FS\n^FO20,220^A0N,30,20^FDPart Number:^FS\n^FO20,255^A0N,45,45^FD{{part}}^FS\n^FO310,220^BY3^BCN,70,Y,N,N^FD{{part}}^FS\n \n^FO20,330^A0N,30,30^FDNuméro de série:^FS\n^FO20,360^A0N,30,20^FDSerial Number:^FS\n^FO20,395^A0N,45,45^FD{{serial}}^FS\n^FO310,360^BY3^BCN,70,Y,N,N^FD{{serial}}^FS\n \n{{upc_zone_start}}\n^FO50,460^BY3^BUN,80,Y,N,Y^FD{{upc_11_digits}}^FS\n{{upc_zone_end}}\n \n^XZ', help_text='ZPL template for shipping box labels. Use {{part}}, {{serial}}, {{upc_full}}, {{upc_11_digits}} as placeholders.', verbose_name='Box Label ZPL Template'),
        ),
        migrations.AlterField(
            model_name='config',
            name='serial_label_zpl',
            field=models.TextField(default='^XA\n^MTT\n^PW406\n^LL176\n^LH0,20\n{{branding_zone_start}}\n^FO12,10^A0,18^FDNe pas enlever (Garantie)/Do not remove (Warranty)^FS\n^FO12,30^A0,25^FDdcalltech.com^FS\n{{branding_zone_end}}\n^FO170,30^A0N,25,30^FD{{part}}^FS\n^FO20,60^BY4^BCN,60,N,N,N,A^FD{{serial}}^FS\n^FO90,130^A0N,20,30^FDSER.#: {{serial}}^FS\n^XZ', help_text='ZPL template for inventory serial number labels. Use {{serial}} for serial number, {{branding_zone_start}} and {{branding_zone_end}} for optional branding.', verbose_name='Serial Label ZPL Template'),
        ),
    ]
