# Generated by Django 6.0.2 on 2026-04-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_config_box_label_zpl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='serial_label_zpl',
            field=models.TextField(default='^XA\n^MTT\n^PW406\n^LL176\n^LH0,20\n^FO12,10^A0,18^FDNe pas enlever (Garantie)/Do not remove (Warranty)^FS\n{{branding_zone_start}}\n^FO12,30^A0,25^FDdcalltech.com^FS\n{{branding_zone_end}}\n^FO170,30^A0N,25,30^FD{{part}}^FS\n^FO20,60^BY4^BCN,60,N,N,N,A^FD{{serial}}^FS\n^FO90,130^A0N,20,30^FDSER.#: {{serial}}^FS\n^XZ', help_text='ZPL template for inventory serial number labels. Use {{serial}} for serial number, {{branding_zone_start}} and {{branding_zone_end}} for optional branding.', verbose_name='Serial Label ZPL Template'),
        ),
    ]
